# Generated by Django 3.1.13 on 2022-04-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
